/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GoogleReviewQrCodeRouteImport } from './routes/google-review-qr-code'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQrRouteImport } from './routes/_authenticated/qr'
import { Route as AuthenticatedPrintStoreRouteImport } from './routes/_authenticated/print-store'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPlacementWizardRouteImport } from './routes/_authenticated/placement-wizard'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBusinessesRouteImport } from './routes/_authenticated/businesses'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedPlacementPlansIndexRouteImport } from './routes/_authenticated/placement-plans.index'
import { Route as AuthenticatedMarketingPacksIndexRouteImport } from './routes/_authenticated/marketing-packs.index'
import { Route as ResourcesCategoryCategoryRouteImport } from './routes/resources.category.$category'
import { Route as RCodeViewRouteImport } from './routes/r.$code_.view'
import { Route as AuthenticatedSettingsEmailRouteImport } from './routes/_authenticated/settings.email'
import { Route as AuthenticatedQrIdRouteImport } from './routes/_authenticated/qr.$id'
import { Route as AuthenticatedPlacementPlansIdRouteImport } from './routes/_authenticated/placement-plans.$id'
import { Route as AuthenticatedMarketingPacksNewRouteImport } from './routes/_authenticated/marketing-packs.new'
import { Route as AuthenticatedMarketingPacksIdRouteImport } from './routes/_authenticated/marketing-packs.$id'
import { Route as AuthenticatedBusinessesIdRouteImport } from './routes/_authenticated/businesses.$id'
import { Route as AuthenticatedAdminWebhookEventsRouteImport } from './routes/_authenticated/admin.webhook-events'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminRegionRequestsRouteImport } from './routes/_authenticated/admin.region-requests'
import { Route as AuthenticatedAdminPrintDemandRouteImport } from './routes/_authenticated/admin.print-demand'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminFunnelRouteImport } from './routes/_authenticated/admin.funnel'
import { Route as AuthenticatedAdminFoundersRouteImport } from './routes/_authenticated/admin.founders'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksEmailWorkerRouteImport } from './routes/api/public/hooks/email-worker'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleReviewQrCodeRoute = GoogleReviewQrCodeRouteImport.update({
  id: '/google-review-qr-code',
  path: '/google-review-qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrRoute = AuthenticatedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintStoreRoute = AuthenticatedPrintStoreRouteImport.update({
  id: '/print-store',
  path: '/print-store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementWizardRoute =
  AuthenticatedPlacementWizardRouteImport.update({
    id: '/placement-wizard',
    path: '/placement-wizard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessesRoute = AuthenticatedBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementPlansIndexRoute =
  AuthenticatedPlacementPlansIndexRouteImport.update({
    id: '/placement-plans/',
    path: '/placement-plans/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingPacksIndexRoute =
  AuthenticatedMarketingPacksIndexRouteImport.update({
    id: '/marketing-packs/',
    path: '/marketing-packs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ResourcesCategoryCategoryRoute =
  ResourcesCategoryCategoryRouteImport.update({
    id: '/resources/category/$category',
    path: '/resources/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const RCodeViewRoute = RCodeViewRouteImport.update({
  id: '/r/$code_/view',
  path: '/r/$code/view',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsEmailRoute =
  AuthenticatedSettingsEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedQrIdRoute = AuthenticatedQrIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedQrRoute,
} as any)
const AuthenticatedPlacementPlansIdRoute =
  AuthenticatedPlacementPlansIdRouteImport.update({
    id: '/placement-plans/$id',
    path: '/placement-plans/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingPacksNewRoute =
  AuthenticatedMarketingPacksNewRouteImport.update({
    id: '/marketing-packs/new',
    path: '/marketing-packs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingPacksIdRoute =
  AuthenticatedMarketingPacksIdRouteImport.update({
    id: '/marketing-packs/$id',
    path: '/marketing-packs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessesIdRoute =
  AuthenticatedBusinessesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBusinessesRoute,
  } as any)
const AuthenticatedAdminWebhookEventsRoute =
  AuthenticatedAdminWebhookEventsRouteImport.update({
    id: '/admin/webhook-events',
    path: '/admin/webhook-events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRegionRequestsRoute =
  AuthenticatedAdminRegionRequestsRouteImport.update({
    id: '/admin/region-requests',
    path: '/admin/region-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPrintDemandRoute =
  AuthenticatedAdminPrintDemandRouteImport.update({
    id: '/admin/print-demand',
    path: '/admin/print-demand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/admin/health',
    path: '/admin/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFunnelRoute =
  AuthenticatedAdminFunnelRouteImport.update({
    id: '/admin/funnel',
    path: '/admin/funnel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFoundersRoute =
  AuthenticatedAdminFoundersRouteImport.update({
    id: '/admin/founders',
    path: '/admin/founders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/admin/email',
  path: '/admin/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailWorkerRoute =
  ApiPublicHooksEmailWorkerRouteImport.update({
    id: '/api/public/hooks/email-worker',
    path: '/api/public/hooks/email-worker',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/google-review-qr-code': typeof GoogleReviewQrCodeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/placement-wizard': typeof AuthenticatedPlacementWizardRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/print-store': typeof AuthenticatedPrintStoreRoute
  '/qr': typeof AuthenticatedQrRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/industries/$slug': typeof IndustriesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/founders': typeof AuthenticatedAdminFoundersRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/print-demand': typeof AuthenticatedAdminPrintDemandRoute
  '/admin/region-requests': typeof AuthenticatedAdminRegionRequestsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/webhook-events': typeof AuthenticatedAdminWebhookEventsRoute
  '/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/marketing-packs/$id': typeof AuthenticatedMarketingPacksIdRoute
  '/marketing-packs/new': typeof AuthenticatedMarketingPacksNewRoute
  '/placement-plans/$id': typeof AuthenticatedPlacementPlansIdRoute
  '/qr/$id': typeof AuthenticatedQrIdRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/r/$code/view': typeof RCodeViewRoute
  '/resources/category/$category': typeof ResourcesCategoryCategoryRoute
  '/marketing-packs/': typeof AuthenticatedMarketingPacksIndexRoute
  '/placement-plans/': typeof AuthenticatedPlacementPlansIndexRoute
  '/api/public/hooks/email-worker': typeof ApiPublicHooksEmailWorkerRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/google-review-qr-code': typeof GoogleReviewQrCodeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/placement-wizard': typeof AuthenticatedPlacementWizardRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/print-store': typeof AuthenticatedPrintStoreRoute
  '/qr': typeof AuthenticatedQrRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/industries/$slug': typeof IndustriesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/founders': typeof AuthenticatedAdminFoundersRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/print-demand': typeof AuthenticatedAdminPrintDemandRoute
  '/admin/region-requests': typeof AuthenticatedAdminRegionRequestsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/webhook-events': typeof AuthenticatedAdminWebhookEventsRoute
  '/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/marketing-packs/$id': typeof AuthenticatedMarketingPacksIdRoute
  '/marketing-packs/new': typeof AuthenticatedMarketingPacksNewRoute
  '/placement-plans/$id': typeof AuthenticatedPlacementPlansIdRoute
  '/qr/$id': typeof AuthenticatedQrIdRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/r/$code/view': typeof RCodeViewRoute
  '/resources/category/$category': typeof ResourcesCategoryCategoryRoute
  '/marketing-packs': typeof AuthenticatedMarketingPacksIndexRoute
  '/placement-plans': typeof AuthenticatedPlacementPlansIndexRoute
  '/api/public/hooks/email-worker': typeof ApiPublicHooksEmailWorkerRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/google-review-qr-code': typeof GoogleReviewQrCodeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/placement-wizard': typeof AuthenticatedPlacementWizardRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/print-store': typeof AuthenticatedPrintStoreRoute
  '/_authenticated/qr': typeof AuthenticatedQrRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/industries/$slug': typeof IndustriesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/founders': typeof AuthenticatedAdminFoundersRoute
  '/_authenticated/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/print-demand': typeof AuthenticatedAdminPrintDemandRoute
  '/_authenticated/admin/region-requests': typeof AuthenticatedAdminRegionRequestsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/webhook-events': typeof AuthenticatedAdminWebhookEventsRoute
  '/_authenticated/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/_authenticated/marketing-packs/$id': typeof AuthenticatedMarketingPacksIdRoute
  '/_authenticated/marketing-packs/new': typeof AuthenticatedMarketingPacksNewRoute
  '/_authenticated/placement-plans/$id': typeof AuthenticatedPlacementPlansIdRoute
  '/_authenticated/qr/$id': typeof AuthenticatedQrIdRoute
  '/_authenticated/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/r/$code_/view': typeof RCodeViewRoute
  '/resources/category/$category': typeof ResourcesCategoryCategoryRoute
  '/_authenticated/marketing-packs/': typeof AuthenticatedMarketingPacksIndexRoute
  '/_authenticated/placement-plans/': typeof AuthenticatedPlacementPlansIndexRoute
  '/api/public/hooks/email-worker': typeof ApiPublicHooksEmailWorkerRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/examples'
    | '/features'
    | '/google-review-qr-code'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/templates'
    | '/terms'
    | '/analytics'
    | '/billing'
    | '/businesses'
    | '/dashboard'
    | '/health'
    | '/placement-wizard'
    | '/plans'
    | '/print-store'
    | '/qr'
    | '/reports'
    | '/settings'
    | '/industries/$slug'
    | '/r/$code'
    | '/resources/$slug'
    | '/industries/'
    | '/resources/'
    | '/admin/email'
    | '/admin/founders'
    | '/admin/funnel'
    | '/admin/health'
    | '/admin/print-demand'
    | '/admin/region-requests'
    | '/admin/seo'
    | '/admin/webhook-events'
    | '/businesses/$id'
    | '/marketing-packs/$id'
    | '/marketing-packs/new'
    | '/placement-plans/$id'
    | '/qr/$id'
    | '/settings/email'
    | '/r/$code/view'
    | '/resources/category/$category'
    | '/marketing-packs/'
    | '/placement-plans/'
    | '/api/public/hooks/email-worker'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/examples'
    | '/features'
    | '/google-review-qr-code'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/templates'
    | '/terms'
    | '/analytics'
    | '/billing'
    | '/businesses'
    | '/dashboard'
    | '/health'
    | '/placement-wizard'
    | '/plans'
    | '/print-store'
    | '/qr'
    | '/reports'
    | '/settings'
    | '/industries/$slug'
    | '/r/$code'
    | '/resources/$slug'
    | '/industries'
    | '/resources'
    | '/admin/email'
    | '/admin/founders'
    | '/admin/funnel'
    | '/admin/health'
    | '/admin/print-demand'
    | '/admin/region-requests'
    | '/admin/seo'
    | '/admin/webhook-events'
    | '/businesses/$id'
    | '/marketing-packs/$id'
    | '/marketing-packs/new'
    | '/placement-plans/$id'
    | '/qr/$id'
    | '/settings/email'
    | '/r/$code/view'
    | '/resources/category/$category'
    | '/marketing-packs'
    | '/placement-plans'
    | '/api/public/hooks/email-worker'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/examples'
    | '/features'
    | '/google-review-qr-code'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/templates'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/businesses'
    | '/_authenticated/dashboard'
    | '/_authenticated/health'
    | '/_authenticated/placement-wizard'
    | '/_authenticated/plans'
    | '/_authenticated/print-store'
    | '/_authenticated/qr'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/industries/$slug'
    | '/r/$code'
    | '/resources/$slug'
    | '/industries/'
    | '/resources/'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/founders'
    | '/_authenticated/admin/funnel'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/print-demand'
    | '/_authenticated/admin/region-requests'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/webhook-events'
    | '/_authenticated/businesses/$id'
    | '/_authenticated/marketing-packs/$id'
    | '/_authenticated/marketing-packs/new'
    | '/_authenticated/placement-plans/$id'
    | '/_authenticated/qr/$id'
    | '/_authenticated/settings/email'
    | '/r/$code_/view'
    | '/resources/category/$category'
    | '/_authenticated/marketing-packs/'
    | '/_authenticated/placement-plans/'
    | '/api/public/hooks/email-worker'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ExamplesRoute: typeof ExamplesRoute
  FeaturesRoute: typeof FeaturesRoute
  GoogleReviewQrCodeRoute: typeof GoogleReviewQrCodeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  RCodeRoute: typeof RCodeRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  RCodeViewRoute: typeof RCodeViewRoute
  ResourcesCategoryCategoryRoute: typeof ResourcesCategoryCategoryRoute
  ApiPublicHooksEmailWorkerRoute: typeof ApiPublicHooksEmailWorkerRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-review-qr-code': {
      id: '/google-review-qr-code'
      path: '/google-review-qr-code'
      fullPath: '/google-review-qr-code'
      preLoaderRoute: typeof GoogleReviewQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr': {
      id: '/_authenticated/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AuthenticatedQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print-store': {
      id: '/_authenticated/print-store'
      path: '/print-store'
      fullPath: '/print-store'
      preLoaderRoute: typeof AuthenticatedPrintStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement-wizard': {
      id: '/_authenticated/placement-wizard'
      path: '/placement-wizard'
      fullPath: '/placement-wizard'
      preLoaderRoute: typeof AuthenticatedPlacementWizardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses': {
      id: '/_authenticated/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AuthenticatedBusinessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement-plans/': {
      id: '/_authenticated/placement-plans/'
      path: '/placement-plans'
      fullPath: '/placement-plans/'
      preLoaderRoute: typeof AuthenticatedPlacementPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-packs/': {
      id: '/_authenticated/marketing-packs/'
      path: '/marketing-packs'
      fullPath: '/marketing-packs/'
      preLoaderRoute: typeof AuthenticatedMarketingPacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/resources/category/$category': {
      id: '/resources/category/$category'
      path: '/resources/category/$category'
      fullPath: '/resources/category/$category'
      preLoaderRoute: typeof ResourcesCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code_/view': {
      id: '/r/$code_/view'
      path: '/r/$code/view'
      fullPath: '/r/$code/view'
      preLoaderRoute: typeof RCodeViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/email': {
      id: '/_authenticated/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AuthenticatedSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/qr/$id': {
      id: '/_authenticated/qr/$id'
      path: '/$id'
      fullPath: '/qr/$id'
      preLoaderRoute: typeof AuthenticatedQrIdRouteImport
      parentRoute: typeof AuthenticatedQrRoute
    }
    '/_authenticated/placement-plans/$id': {
      id: '/_authenticated/placement-plans/$id'
      path: '/placement-plans/$id'
      fullPath: '/placement-plans/$id'
      preLoaderRoute: typeof AuthenticatedPlacementPlansIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-packs/new': {
      id: '/_authenticated/marketing-packs/new'
      path: '/marketing-packs/new'
      fullPath: '/marketing-packs/new'
      preLoaderRoute: typeof AuthenticatedMarketingPacksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-packs/$id': {
      id: '/_authenticated/marketing-packs/$id'
      path: '/marketing-packs/$id'
      fullPath: '/marketing-packs/$id'
      preLoaderRoute: typeof AuthenticatedMarketingPacksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses/$id': {
      id: '/_authenticated/businesses/$id'
      path: '/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof AuthenticatedBusinessesIdRouteImport
      parentRoute: typeof AuthenticatedBusinessesRoute
    }
    '/_authenticated/admin/webhook-events': {
      id: '/_authenticated/admin/webhook-events'
      path: '/admin/webhook-events'
      fullPath: '/admin/webhook-events'
      preLoaderRoute: typeof AuthenticatedAdminWebhookEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/region-requests': {
      id: '/_authenticated/admin/region-requests'
      path: '/admin/region-requests'
      fullPath: '/admin/region-requests'
      preLoaderRoute: typeof AuthenticatedAdminRegionRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/print-demand': {
      id: '/_authenticated/admin/print-demand'
      path: '/admin/print-demand'
      fullPath: '/admin/print-demand'
      preLoaderRoute: typeof AuthenticatedAdminPrintDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funnel': {
      id: '/_authenticated/admin/funnel'
      path: '/admin/funnel'
      fullPath: '/admin/funnel'
      preLoaderRoute: typeof AuthenticatedAdminFunnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/founders': {
      id: '/_authenticated/admin/founders'
      path: '/admin/founders'
      fullPath: '/admin/founders'
      preLoaderRoute: typeof AuthenticatedAdminFoundersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/admin/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-worker': {
      id: '/api/public/hooks/email-worker'
      path: '/api/public/hooks/email-worker'
      fullPath: '/api/public/hooks/email-worker'
      preLoaderRoute: typeof ApiPublicHooksEmailWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBusinessesRouteChildren {
  AuthenticatedBusinessesIdRoute: typeof AuthenticatedBusinessesIdRoute
}

const AuthenticatedBusinessesRouteChildren: AuthenticatedBusinessesRouteChildren =
  {
    AuthenticatedBusinessesIdRoute: AuthenticatedBusinessesIdRoute,
  }

const AuthenticatedBusinessesRouteWithChildren =
  AuthenticatedBusinessesRoute._addFileChildren(
    AuthenticatedBusinessesRouteChildren,
  )

interface AuthenticatedQrRouteChildren {
  AuthenticatedQrIdRoute: typeof AuthenticatedQrIdRoute
}

const AuthenticatedQrRouteChildren: AuthenticatedQrRouteChildren = {
  AuthenticatedQrIdRoute: AuthenticatedQrIdRoute,
}

const AuthenticatedQrRouteWithChildren = AuthenticatedQrRoute._addFileChildren(
  AuthenticatedQrRouteChildren,
)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsEmailRoute: typeof AuthenticatedSettingsEmailRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsEmailRoute: AuthenticatedSettingsEmailRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBusinessesRoute: typeof AuthenticatedBusinessesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedPlacementWizardRoute: typeof AuthenticatedPlacementWizardRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPrintStoreRoute: typeof AuthenticatedPrintStoreRoute
  AuthenticatedQrRoute: typeof AuthenticatedQrRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminFoundersRoute: typeof AuthenticatedAdminFoundersRoute
  AuthenticatedAdminFunnelRoute: typeof AuthenticatedAdminFunnelRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminPrintDemandRoute: typeof AuthenticatedAdminPrintDemandRoute
  AuthenticatedAdminRegionRequestsRoute: typeof AuthenticatedAdminRegionRequestsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminWebhookEventsRoute: typeof AuthenticatedAdminWebhookEventsRoute
  AuthenticatedMarketingPacksIdRoute: typeof AuthenticatedMarketingPacksIdRoute
  AuthenticatedMarketingPacksNewRoute: typeof AuthenticatedMarketingPacksNewRoute
  AuthenticatedPlacementPlansIdRoute: typeof AuthenticatedPlacementPlansIdRoute
  AuthenticatedMarketingPacksIndexRoute: typeof AuthenticatedMarketingPacksIndexRoute
  AuthenticatedPlacementPlansIndexRoute: typeof AuthenticatedPlacementPlansIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBusinessesRoute: AuthenticatedBusinessesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedPlacementWizardRoute: AuthenticatedPlacementWizardRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPrintStoreRoute: AuthenticatedPrintStoreRoute,
  AuthenticatedQrRoute: AuthenticatedQrRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
  AuthenticatedAdminFoundersRoute: AuthenticatedAdminFoundersRoute,
  AuthenticatedAdminFunnelRoute: AuthenticatedAdminFunnelRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminPrintDemandRoute: AuthenticatedAdminPrintDemandRoute,
  AuthenticatedAdminRegionRequestsRoute: AuthenticatedAdminRegionRequestsRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminWebhookEventsRoute: AuthenticatedAdminWebhookEventsRoute,
  AuthenticatedMarketingPacksIdRoute: AuthenticatedMarketingPacksIdRoute,
  AuthenticatedMarketingPacksNewRoute: AuthenticatedMarketingPacksNewRoute,
  AuthenticatedPlacementPlansIdRoute: AuthenticatedPlacementPlansIdRoute,
  AuthenticatedMarketingPacksIndexRoute: AuthenticatedMarketingPacksIndexRoute,
  AuthenticatedPlacementPlansIndexRoute: AuthenticatedPlacementPlansIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ExamplesRoute: ExamplesRoute,
  FeaturesRoute: FeaturesRoute,
  GoogleReviewQrCodeRoute: GoogleReviewQrCodeRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  RCodeRoute: RCodeRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  RCodeViewRoute: RCodeViewRoute,
  ResourcesCategoryCategoryRoute: ResourcesCategoryCategoryRoute,
  ApiPublicHooksEmailWorkerRoute: ApiPublicHooksEmailWorkerRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
