/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQrRouteImport } from './routes/_authenticated/qr'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBusinessesRouteImport } from './routes/_authenticated/businesses'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedMarketingPacksIndexRouteImport } from './routes/_authenticated/marketing-packs.index'
import { Route as AuthenticatedQrIdRouteImport } from './routes/_authenticated/qr.$id'
import { Route as AuthenticatedMarketingPacksNewRouteImport } from './routes/_authenticated/marketing-packs.new'
import { Route as AuthenticatedMarketingPacksIdRouteImport } from './routes/_authenticated/marketing-packs.$id'
import { Route as AuthenticatedBusinessesIdRouteImport } from './routes/_authenticated/businesses.$id'
import { Route as AuthenticatedAdminRegionRequestsRouteImport } from './routes/_authenticated/admin.region-requests'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrRoute = AuthenticatedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessesRoute = AuthenticatedBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingPacksIndexRoute =
  AuthenticatedMarketingPacksIndexRouteImport.update({
    id: '/marketing-packs/',
    path: '/marketing-packs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQrIdRoute = AuthenticatedQrIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedQrRoute,
} as any)
const AuthenticatedMarketingPacksNewRoute =
  AuthenticatedMarketingPacksNewRouteImport.update({
    id: '/marketing-packs/new',
    path: '/marketing-packs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingPacksIdRoute =
  AuthenticatedMarketingPacksIdRouteImport.update({
    id: '/marketing-packs/$id',
    path: '/marketing-packs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessesIdRoute =
  AuthenticatedBusinessesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBusinessesRoute,
  } as any)
const AuthenticatedAdminRegionRequestsRoute =
  AuthenticatedAdminRegionRequestsRouteImport.update({
    id: '/admin/region-requests',
    path: '/admin/region-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/qr': typeof AuthenticatedQrRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/r/$code': typeof RCodeRoute
  '/admin/region-requests': typeof AuthenticatedAdminRegionRequestsRoute
  '/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/marketing-packs/$id': typeof AuthenticatedMarketingPacksIdRoute
  '/marketing-packs/new': typeof AuthenticatedMarketingPacksNewRoute
  '/qr/$id': typeof AuthenticatedQrIdRoute
  '/marketing-packs/': typeof AuthenticatedMarketingPacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/qr': typeof AuthenticatedQrRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/r/$code': typeof RCodeRoute
  '/admin/region-requests': typeof AuthenticatedAdminRegionRequestsRoute
  '/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/marketing-packs/$id': typeof AuthenticatedMarketingPacksIdRoute
  '/marketing-packs/new': typeof AuthenticatedMarketingPacksNewRoute
  '/qr/$id': typeof AuthenticatedQrIdRoute
  '/marketing-packs': typeof AuthenticatedMarketingPacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/qr': typeof AuthenticatedQrRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/r/$code': typeof RCodeRoute
  '/_authenticated/admin/region-requests': typeof AuthenticatedAdminRegionRequestsRoute
  '/_authenticated/businesses/$id': typeof AuthenticatedBusinessesIdRoute
  '/_authenticated/marketing-packs/$id': typeof AuthenticatedMarketingPacksIdRoute
  '/_authenticated/marketing-packs/new': typeof AuthenticatedMarketingPacksNewRoute
  '/_authenticated/qr/$id': typeof AuthenticatedQrIdRoute
  '/_authenticated/marketing-packs/': typeof AuthenticatedMarketingPacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/businesses'
    | '/dashboard'
    | '/pricing'
    | '/qr'
    | '/settings'
    | '/r/$code'
    | '/admin/region-requests'
    | '/businesses/$id'
    | '/marketing-packs/$id'
    | '/marketing-packs/new'
    | '/qr/$id'
    | '/marketing-packs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/businesses'
    | '/dashboard'
    | '/pricing'
    | '/qr'
    | '/settings'
    | '/r/$code'
    | '/admin/region-requests'
    | '/businesses/$id'
    | '/marketing-packs/$id'
    | '/marketing-packs/new'
    | '/qr/$id'
    | '/marketing-packs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/businesses'
    | '/_authenticated/dashboard'
    | '/_authenticated/pricing'
    | '/_authenticated/qr'
    | '/_authenticated/settings'
    | '/r/$code'
    | '/_authenticated/admin/region-requests'
    | '/_authenticated/businesses/$id'
    | '/_authenticated/marketing-packs/$id'
    | '/_authenticated/marketing-packs/new'
    | '/_authenticated/qr/$id'
    | '/_authenticated/marketing-packs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr': {
      id: '/_authenticated/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AuthenticatedQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses': {
      id: '/_authenticated/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AuthenticatedBusinessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-packs/': {
      id: '/_authenticated/marketing-packs/'
      path: '/marketing-packs'
      fullPath: '/marketing-packs/'
      preLoaderRoute: typeof AuthenticatedMarketingPacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr/$id': {
      id: '/_authenticated/qr/$id'
      path: '/$id'
      fullPath: '/qr/$id'
      preLoaderRoute: typeof AuthenticatedQrIdRouteImport
      parentRoute: typeof AuthenticatedQrRoute
    }
    '/_authenticated/marketing-packs/new': {
      id: '/_authenticated/marketing-packs/new'
      path: '/marketing-packs/new'
      fullPath: '/marketing-packs/new'
      preLoaderRoute: typeof AuthenticatedMarketingPacksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-packs/$id': {
      id: '/_authenticated/marketing-packs/$id'
      path: '/marketing-packs/$id'
      fullPath: '/marketing-packs/$id'
      preLoaderRoute: typeof AuthenticatedMarketingPacksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses/$id': {
      id: '/_authenticated/businesses/$id'
      path: '/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof AuthenticatedBusinessesIdRouteImport
      parentRoute: typeof AuthenticatedBusinessesRoute
    }
    '/_authenticated/admin/region-requests': {
      id: '/_authenticated/admin/region-requests'
      path: '/admin/region-requests'
      fullPath: '/admin/region-requests'
      preLoaderRoute: typeof AuthenticatedAdminRegionRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedBusinessesRouteChildren {
  AuthenticatedBusinessesIdRoute: typeof AuthenticatedBusinessesIdRoute
}

const AuthenticatedBusinessesRouteChildren: AuthenticatedBusinessesRouteChildren =
  {
    AuthenticatedBusinessesIdRoute: AuthenticatedBusinessesIdRoute,
  }

const AuthenticatedBusinessesRouteWithChildren =
  AuthenticatedBusinessesRoute._addFileChildren(
    AuthenticatedBusinessesRouteChildren,
  )

interface AuthenticatedQrRouteChildren {
  AuthenticatedQrIdRoute: typeof AuthenticatedQrIdRoute
}

const AuthenticatedQrRouteChildren: AuthenticatedQrRouteChildren = {
  AuthenticatedQrIdRoute: AuthenticatedQrIdRoute,
}

const AuthenticatedQrRouteWithChildren = AuthenticatedQrRoute._addFileChildren(
  AuthenticatedQrRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBusinessesRoute: typeof AuthenticatedBusinessesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedQrRoute: typeof AuthenticatedQrRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminRegionRequestsRoute: typeof AuthenticatedAdminRegionRequestsRoute
  AuthenticatedMarketingPacksIdRoute: typeof AuthenticatedMarketingPacksIdRoute
  AuthenticatedMarketingPacksNewRoute: typeof AuthenticatedMarketingPacksNewRoute
  AuthenticatedMarketingPacksIndexRoute: typeof AuthenticatedMarketingPacksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBusinessesRoute: AuthenticatedBusinessesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedQrRoute: AuthenticatedQrRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminRegionRequestsRoute: AuthenticatedAdminRegionRequestsRoute,
  AuthenticatedMarketingPacksIdRoute: AuthenticatedMarketingPacksIdRoute,
  AuthenticatedMarketingPacksNewRoute: AuthenticatedMarketingPacksNewRoute,
  AuthenticatedMarketingPacksIndexRoute: AuthenticatedMarketingPacksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
